"""orderrating

Revision ID: 14435b1f1a68
Revises: 094d9361db3a
Create Date: 2020-11-26 14:52:54.704780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14435b1f1a68'
down_revision = '094d9361db3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderRatings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderRatings',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"OrderRatings_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('byUser', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('toUser', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('forOrder', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['byUser'], ['Users.id'], name='OrderRatings_byUser_fkey'),
    sa.ForeignKeyConstraint(['forOrder'], ['Orders.id'], name='OrderRatings_forOrder_fkey'),
    sa.ForeignKeyConstraint(['toUser'], ['Users.id'], name='OrderRatings_toUser_fkey'),
    sa.PrimaryKeyConstraint('id', name='OrderRatings_pkey')
    )
    # ### end Alembic commands ###
