"""restart

Revision ID: 28e293a4defd
Revises: 6cb03e2e9a43
Create Date: 2020-11-28 18:08:53.232224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e293a4defd'
down_revision = '6cb03e2e9a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
