"""second

Revision ID: 73c502e60f1d
Revises: 97924c072312
Create Date: 2020-11-23 17:43:12.785890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c502e60f1d'
down_revision = '97924c072312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'test')
    # ### end Alembic commands ###
