"""init

Revision ID: 97924c072312
Revises: 6184b6ad8c97
Create Date: 2020-11-23 17:41:27.464513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97924c072312'
down_revision = '6184b6ad8c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
