"""country phone prefix

Revision ID: d50fe8a82726
Revises: b694f9557573
Create Date: 2020-11-24 00:02:39.626613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50fe8a82726'
down_revision = 'b694f9557573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Countries', sa.Column('phonePrefix', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Countries', 'phonePrefix')
    # ### end Alembic commands ###
